-- AlterTable
ALTER TABLE `submission` MODIFY `status` ENUM('PENDING', 'PROCESSING', 'FAILED', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR') NOT NULL DEFAULT 'PENDING';
